TOKEN_TYPES_LIST = ["IDENTIFIER", "KEYWORD", "STRING", "CHAR", "INTEGER",
                    "FLOAT", "HEXADECIMAL", "COMMENT", "WHITESPACE", "OPERATOR",
                    "SEPARATOR", "ERROR", "INVALID_TOKEN"]
